<?xml version="1.0"?>
<!--
   Created Or Edited on: 23/09/2015
   Author: Zach
           qoogood1234@gmail.com
   Edited on: 29/09/2015
   Author: Dott. Antonio Mauro Galiano
 	   antoniomauro.galiano@gmail.com
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="andbot">
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="length_wheel" value="0.0254"/>
  <xacro:property name="radius_wheel" value="0.076"/>
  <xacro:property name="distance_between_wheels" value="0.393"/>
  <xacro:property name="height_wheels_from_base" value="0.0392"/>
 
 <arg name="gui" value="true"/>
  <!-- Base footprint link-->
  <link name="base_footprint"/>


  <link name="xv11">
  </link>
  <joint name="xv11_fixed" type="fixed">
    <parent link="base_footprint"/>
    <child link="xv11"/>
	
<!--    plastic model     -->

  <origin xyz="-0.022 0 ${radius_wheel+0.135}" rpy="0 0 0"/>

<!--	metal model	-->
<!--	<origin xyz="0.07 0 ${radius_wheel+0.135}" rpy="0 0 0"/>-->
  </joint>

  <joint name="IMU_joint" type="fixed">
    <axis xyz="1 0 0"/>      
        <origin xyz="0.0 0.0 0.055"/>
	    <parent link="base_link"/>
	    <child link="IMU_link"/>
  </joint>

  <link name="IMU_link"/>
<!-- Base link -->
  <link name="base_link"/>

<!-- Base footprint link / Base link joint -->
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint>

</robot>
